# This is the control file for Travis continuous integration system.
#
# It is used automatically for the repositories on Github if it's found in the
# root directory of the project.
language: cpp
sudo: required

matrix:
    include:
        - dist: trusty
          compiler: gcc
          env: wxTOOLSET=cmake wxCMAKE_GENERATOR="Unix Makefiles"
        - os: osx
          osx_image: beta-xcode6.2
          compiler: clang
          env: wxTOOLSET=cmake wxCMAKE_GENERATOR=Xcode wxCMAKE_DEFINES="-DCMAKE_CXX_STANDARD=11"
        - compiler: gcc
        - compiler: gcc
          env: wxCONFIGURE_FLAGS="--disable-precomp-headers --enable-monolithic"
        - dist: trusty
          compiler: gcc
        - dist: trusty
          compiler: gcc
          env: wxCONFIGURE_FLAGS="--enable-cxx11 --enable-stl" wxMAKEFILE_FLAGS="CXXFLAGS=-std=c++11"
        - dist: trusty
          compiler: clang
          env: wxCONFIGURE_FLAGS="--disable-shared"
        - os: osx
          osx_image: xcode6.4
          compiler: clang
          env: wxCONFIGURE_FLAGS="--enable-cxx11" wxMAKEFILE_FLAGS="CXXFLAGS='-std=c++11 -stdlib=libc++'"

branches:
    only:
        - master
        - WX_3_0_BRANCH

notifications:
    email:
        recipients:
            - vadim@wxwidgets.org
        on_success: change
        on_failure: change

before_install: ./build/tools/before_install.sh

script: bash build/tools/travis-ci.sh
